name = "pro-tools-website"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[env.production]
name = "pro-tools-website"

# Environment variables (set these in Cloudflare Dashboard)
# BOT_TOKEN = "your_telegram_bot_token"
# ADMIN_USER = "your_admin_username"
# ADMIN_PASS = "your_admin_password"

# KV Namespace bindings
[[env.production.kv_namespaces]]
binding = "DATABASE"
id = "your_kv_namespace_id"
preview_id = "your_preview_kv_namespace_id"

# For development
[[kv_namespaces]]
binding = "DATABASE"
id = "your_kv_namespace_id"
preview_id = "your_preview_kv_namespace_id"
